package com.sparta.payment_system.dto;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
public class PortOnePaymentResponse {
    
    private String impUid;
    private String merchantUid;
    private String status;
    private String payMethod;
    private String channel;
    private String pgProvider;
    private String embPgProvider;
    private String pgTid;
    private String pgId;
    private String escrow;
    private String applyNum;
    private String bankCode;
    private String bankName;
    private String cardCode;
    private String cardName;
    private String cardNumber;
    private String cardQuota;
    private String cardType;
    private String vbankCode;
    private String vbankName;
    private String vbankNum;
    private String vbankHolder;
    private String vbankDate;
    private String vbankIssuedAt;
    private String name;
    private Integer amount;
    private Integer cancelAmount;
    private String currency;
    private String buyerName;
    private String buyerEmail;
    private String buyerTel;
    private String buyerAddr;
    private String buyerPostcode;
    private String customData;
    private String userAgent;
    private String statusMessage;
    private String failReason;
    private String cancelReason;
    private String receiptUrl;
    private String cashReceiptIssued;
    private String customerUid;
    private String customerUidUsage;
    private String startedAt;
    private String paidAt;
    private String failedAt;
    private String cancelledAt;
    private String failReasonMessage;
    private String cancelHistory;
    private String cancelReceiptUrls;
    private String cashReceipt;
    private String cashReceipts;
    private String discount;
    private String cardDetail;
    private String digitalReceipt;
    private String receipt;
    private String easyPay;
    private String country;
    private String checksum;
    private String type;
    private String payMethodDetail;
    private String impUidList;
    private String merchantUidList;
    private String pgProviderList;
    private String pgTidList;
    private String pgIdList;
    private String escrowList;
    private String applyNumList;
    private String bankCodeList;
    private String bankNameList;
    private String cardCodeList;
    private String cardNameList;
    private String cardNumberList;
    private String cardQuotaList;
    private String cardTypeList;
    private String vbankCodeList;
    private String vbankNameList;
    private String vbankNumList;
    private String vbankHolderList;
    private String vbankDateList;
    private String vbankIssuedAtList;
    private String nameList;
    private String amountList;
    private String cancelAmountList;
    private String currencyList;
    private String buyerNameList;
    private String buyerEmailList;
    private String buyerTelList;
    private String buyerAddrList;
    private String buyerPostcodeList;
    private String customDataList;
    private String userAgentList;
    private String statusMessageList;
    private String failReasonList;
    private String cancelReasonList;
    private String receiptUrlList;
    private String cashReceiptIssuedList;
    private String customerUidList;
    private String customerUidUsageList;
    private String startedAtList;
    private String paidAtList;
    private String failedAtList;
    private String cancelledAtList;
    private String failReasonMessageList;
    private String cancelHistoryList;
    private String cancelReceiptUrlsList;
    private String cashReceiptList;
    private String cashReceiptsList;
    private String discountList;
    private String cardDetailList;
    private String digitalReceiptList;
    private String receiptList;
    private String easyPayList;
    private String countryList;
    private String checksumList;
    private String typeList;
    private String payMethodDetailList;
}
