version: 0.0
os: linux
files:
  - source: / # buildspec에서 base-directory 기준으로 .jar 파일만 zip파일 루트에 담깁니다.
    destination: /home/ec2-user/sparta-cloud-payment-system/payment-system 

permissions:
  - object: /home/ec2-user/sparta-cloud-payment-system/payment-system
    owner: ec2-user
    group: ec2-user
    mode: 755
  # 스크립트 실행 권한 추가
  - object: /home/ec2-user/sparta-cloud-payment-system/payment-system/scripts
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  - object: /home/ec2-user/sparta-cloud-payment-system/payment-system/scripts/
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file

hooks:
  ApplicationStop: # 새 버전을 배포하기 전, 기존 앱 중지
    - location: scripts/stop.sh # appspec.yml 기준 상대 경로입니다.
      timeout: 60
      runas: ec2-user # root 대신 ec2-user로 실행하는 것이 더 안전합니다.
  ApplicationStart: # 파일 복사가 끝난 후, 새 앱 시작
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user
